Global:
  use_gpu: '0,1,2,3'
  epoch_num: 400
  log_smooth_window: 20
  print_batch_step: 5
  checkpoints: /workspace/JuneLi/bbtv/ExpCode/RARE/inference_model/baidu/infer/table_rec/pd2pt.pt
#  checkpoints: /workspace/JuneLi/bbtv/ExpCode/RARE/inference_model/juneli/finetune/table_rec/last.pt
  save_model_dir: ./inference_model/juneli/finetune/table_rec/
  save_epoch_step: 1
  # evaluation is run every 1000 iterations after the 0th iteration
  eval_batch_step: 1000
  cal_metric_during_train: True
  # for data or label process
  character_dict_path: utils/dict/table_structure_dict.txt
  character_type: en
  max_text_length: 100
  max_elem_length: 800
  max_cell_num: 500
  process_total_num: 0
  process_cut_num: 0

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 5.0
  lr:
    learning_rate: 0.0001
  regularizer:
    name: 'L2'
    factor: 0.00000

Architecture:
  model_type: table
  algorithm: TableAttn
  Backbone:
    name: MobileNetV3
    scale: 1.0
    model_name: large
  Head:
    name: TableAttentionHead
    hidden_size: 256
    l2_decay: 0.00001
    loc_type: 2
    max_text_length: 100
    max_elem_length: 800
    max_cell_num: 500

Loss:
  name: TableAttentionLoss
  structure_weight: 100.0
  loc_weight: 10000.0

PostProcess:
  name: TableLabelDecode

Metric:
  name: TableMetric
  main_indicator: acc

Train:
  dataset:
    name: PubTabDataSet
    data_dir: /workspace/JuneLi/bbtv/ExpCode/RARE/datasets/private/FundScan/images/
    label_file_path: /workspace/JuneLi/bbtv/ExpCode/RARE/datasets/private/FundScan/train.json
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - ResizeTableImage:
          max_len: 488
      - TableLabelEncode:
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'structure', 'bbox_list', 'sp_tokens', 'bbox_list_mask']
  loader:
    shuffle: True
    batch_size_per_card: 24
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: PubTabDataSet
    data_dir: /workspace/JuneLi/bbtv/ExpCode/RARE/datasets/private/FundScan/images/
    label_file_path: /workspace/JuneLi/bbtv/ExpCode/RARE/datasets/private/FundScan/val.json
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - ResizeTableImage:
          max_len: 488
      - TableLabelEncode:
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'structure', 'bbox_list', 'sp_tokens', 'bbox_list_mask']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 32
    num_workers: 4
